protected/models/Pdf.php
<?php

/**
 * This is the model class for table "pdf".
 *
 * The followings are the available columns in table 'pdf':
 * @property integer $id
 * @property integer $generated
 * @property string $from_date
 * @property string $to_date
 * @property string $created_at
 * @property string $media_url
 */
class Pdf extends BaseModels
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'pdf';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('from_date, to_date, created_at', 'required'),
			array('media_url', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, from_date, to_date, created_at, media_url,pagination_size', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		$array=array(
			'id' => 'ID',
			'from_date' => 'From Date',
			'to_date' => 'To Date',
			'created_at' => 'Created At',
			'generated' => 'Generated',
			'media_url' => 'PDF File',
			'visible_media_url'=>'PDF file'
		);
		return array_merge($this->Labels(),$array);

	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.
		if(isset($this->pagination_size))
			$pages = $this->pagination_size;
		else
			$pages=5;
		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('from_date',$this->from_date,true);
		$criteria->compare('to_date',$this->to_date,true);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('generated','<2',true);
		$criteria->compare('media_url',$this->media_url,true);

		return new CActiveDataProvider($this, array(
			'pagination' => array('pageSize' => $pages),
			'criteria'=>$criteria,
		));
	}

	public function get_not_generated(){
		return $this->findAll('generated = 0');
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Pdf the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/PdfController.php
<?php

class PdfController extends BaseController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','create','index','view'),
				'users'=>array(Yii::app()->user->getState('type')),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		$model->generated =2;
		$model->save();
		/*$file = Yii::app()->params['webroot'].$model->media_url;

		if(file_exists($file)){
			$html = explode('.',$file);
			if(file_exists($html[0].'.html')){
				unlink($file) ;
				unlink($html[0].'.html');
				$model->delete();
			}
		}*/
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Pdf;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);


		if(isset($_POST['Pdf']))
		{
			$valid = true;
			$model->attributes=$_POST['Pdf'];
			$model->created_at = date('Y-m-d H:i:s');
			if(strtotime($model->from_date) > strtotime($model->to_date)){
				$model->addError('from_date','Please check date ');
				$model->addError('to_date','Please check date ');
				$valid = false;
			}

			if($valid){
				$model->media_url = null;
				if($model->save(true))
				{
					Yii::app()->user->setFlash('success', "System will generate pdf file shortly .. ");
				}
			}
		}
		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function load_data($data){

		$items = array();
		foreach ($data as $item) {
			$items[] = $item->attributes;
		}
		return $items;
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Pdf('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Pdf'])) {
			$this->data_search = $_GET['Pdf'];
			$this->data_search($model);

			$model->attributes = $_GET['Pdf'];
		}
		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Pdf the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Pdf::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Pdf $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='pdf-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/pdf/_form.php
<?php
/* @var $this PdfController */
/* @var $model Pdf */
/* @var $form TbActiveForm */
?>
	<style>
		.showhideitem{
			display: block;
		}
	</style>
<div class="col-sm-12">
	<?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
		'id'=>'pdf-form',
		'enableAjaxValidation'=>true,
		'type' => 'horizontal',
	));
	$field = 'col-sm-11';
	$label = 'col-sm-1';
	echo $form->errorSummary($model);

	$date = date('Y-m-d');
	$date1 = str_replace('-', '/', $date);
	$tomorrow = date('Y-m-d',strtotime($date1 . "+1 days"));
	echo $form->datePickerGroup($model,'from_date',array(
		'widgetOptions' => array(
			'options' => array(
				'language' => 'en',
				'format' => 'yyyy-mm-dd',
				//'startDate'=>$date,
				'viewformat' => 'yyyy-mm-dd',
			),

		),
		'labelOptions' => array(
			'class' => $label,
		),
		'wrapperHtmlOptions' => array(
			'class' => $field,

		),

		'prepend' => '<i class="fa fa-calendar"></i>'
	)); ?>

	<?php echo $form->datePickerGroup($model,'to_date',array(
		'widgetOptions' => array(
			'options' => array(
				'language' => 'en',
				'format' => 'yyyy-mm-dd',
				//'startDate'=>$tomorrow,
				'viewformat' => 'yyyy-mm-dd',
			),

		),
		'labelOptions' => array(
			'class' => $label,
		),
		'wrapperHtmlOptions' => array(
			'class' => $field,
		),
		'prepend' => '<i class="fa fa-calendar"></i>'
	)); ?>
	<div class="form-actions col-md-12  pull-right" style="margin-bottom: 20px;margin-right: -15px;">
		<?php $this->widget(
			'booster.widgets.TbButton',
			array(
				'buttonType' => 'submit',
				'context' => 'primary',
				'label' => 'Download',
				'htmlOptions'=>array(
					'class'=>'pull-right'
				)
			)
		); ?>

	</div>
	<?php $this->endWidget(); ?>
</div><!-- form -->

<?php
$createLink = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=seventeen'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'firstPdf',
		'title'        => 'From Date',
		'next'         => 'second',
		'buttons'      => array(
			array('name'=>'Previous','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$createLink';}"),

			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'input start date of the pdf you wanted',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#Pdf_from_date',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'second',
		'title'        => 'To Date',
		'next'         => 'third',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('firstPdf');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'input end date of the pdf you wanted',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#Pdf_to_date',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>

<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'third',
		'title'        => 'Create PDF',
		'next'         => 'fourth',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('second');}"
			),
			array(
				'name'   => 'Next',
				'onclick'=> "js:function(){ $('#yw1').addClass('showhideitem'); guiders.hideAll(); $('.highlight pre').hide(); guiders.show('createPdf'); }"
			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Press and your PDF will be downloaded',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#yw4',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php
$createTemplate = Yii::app()->createUrl('pdf/admin',array('#' => 'guider=firstpdf'));
$continueTour = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=seventeen'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'createPdf',
		'title'        => 'Action Manage',
		'next'         => 'third',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('third');$('#yw1').removeClass('showhideitem') }"
			),
			array('name'=>'Continue ','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$continueTour';}"),

			array('name'=>'Manage Tour','classString' => 'tourcolor','onclick'=> "js:function(){   document.location = '$createTemplate'; }"),


			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll(); $('#yw1').removeClass('showhideitem') }"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Here you will find all downloaded Pdfs ',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#yw1',
		'position'      => 9,
		'xButton'       => false,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php
$Previous = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=postQueueTour'));
$continueTour = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=FinalStepTour'));
$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'PDFTour',
		'title'        => 'PDF file',
		'next' =>'EditPostsTour',
		'buttons'      => array(
			array('name'=>'Previous ','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$Previous';}"),

			array('name'=>'Next ','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$continueTour';}"),



			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?

		'description'   => 'You can also export the created content into a PDF file, should you wish to share the content with your colleagues, supervisors or clients. ',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#PDFtour',
		'position'      => 3,
		'xButton'       => true,
		'autoFocus'      => true,
		'closeOnEscape' => true,
	)
);
?>

protected/views/pdf/admin.php
<?php
/* @var $this PdfController */
/* @var $model Pdf */

$this->pageTitle = "PDF | Admin";

$this->breadcrumbs=array(
	'PDF File'=>array('admin'),
	'Manage',
);
Yii::app()->clientScript->registerScript('search', "
$('#form-visible').change(function(){
	$(this).submit();
	return true;
});
$('.search-form form').submit(function(){
	$('#pdf-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
	<style>
		.checkbox {
			display: block;
			min-height: 0px;
			margin-top: 4px;
			margin-bottom: 0px;
			padding-left: 17px;
		}
		.input-group-addon input[type=radio], .input-group-addon input[type=checkbox] {
			margin-top: 0;
		}
		.radio input[type=radio], .radio-inline input[type=radio], .checkbox input[type=checkbox], .checkbox-inline input[type=checkbox] {
			float: left;
			margin-left: -16px;
		}
	</style>

<section class="content">
	<div class="row">
		<div class="col-sm-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<div class="col-sm-9"><?PHP
						$this->widget(
							'booster.widgets.TbButtonGroup',
							array(
								'size' => 'small',
								'context' => 'info',
								'buttons' => array(
									array(
										'label' => 'Create',
										'buttonType' =>'link',
										'url' => array('pdf/index')
									),
								),

							)
						);

						?></div>
					<div class="col-sm-3" style="text-align: left;">
						<?php echo Yii::app()->params['statement']['previousPage']; ?>





					</div>
				</div>
				<div class="box-body">
<!--					--><?PHP /*echo $this->renderPartial('_search',array('model'=>$model),true) */?>

					<?PHP
					$form=$this->beginWidget('booster.widgets.TbActiveForm', array(
						'action'=>Yii::app()->createUrl($this->route),
						'method'=>'get',
						'id'=>'form-visible',
					));
					?>
					<div class="col-sm-2 pull-left page-sizes"  >

						<?php echo $form->dropDownListGroup(
							$model,
							'pagination_size',
							array(

								'widgetOptions'=>array(
									'data'=>$model->pages_size(),
									'htmlOptions'=>array(

									),
								),
								'hint'=>''
							)
						); ?>
					</div>
					<?php
					$this->endWidget();
					$this->widget('booster.widgets.TbGridView', array(
						'id'=>'platform-grid',
						'type' => 'striped bordered condensed',
						'template' => '{pager}{items}{summary}{pager}',
						'enablePagination' => true,
						'pager' => array(
							'class' => 'booster.widgets.TbPager',
							'nextPageLabel' => 'Next',
							'prevPageLabel' => 'Previous',
							'htmlOptions' => array(
								'class' => 'pull-right'
							)
						),
						'htmlOptions' => array(
							'class' => 'table-responsive'
						),
						'filter' => $model,

						'dataProvider' => $model->search(),
						'rowCssClassExpression'=>'$data->generated == 1?"active":"danger"',
 						'columns' => array(
							array(
								'name'=>'id',
								'visible'=>$model->visible_id?true:false,
							),
							array(
								'name'=>'from_date',
								'visible'=>$model->visible_from_date?true:false,

							),
							array(
								'name'=>'to_date',
								'visible'=>$model->visible_to_date?true:false,

							),							array(
								'name'=>'media_url',
								'value'=>'$data->generated==1?CHtml::link("PDF File" ,$data->media_url,array("target"=>"_blank")): "Processing "',
								'type'=>'raw',
								'visible'=>$model->visible_media_url?true:false,

							),
							array(
								'name'=>'created_at',
								'visible'=>$model->visible_created_at?true:false,

							),

							array(
								'class' => 'booster.widgets.TbButtonColumn',
								'header' => 'Options',
								'template' => '{delete}',
								'buttons' => array(
									'delete' => array(
										'label' => 'Delete',
										'icon' => 'fa fa-times',
									),
								)
							),
						)));?>
				</div>
			</div>
		</div>
</section>

<!--Tour -->
<?php
$createLink = Yii::app()->createUrl('pdf',array('#' => 'guider=third'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'firstpdf',
		'title'        => 'From Date',
		'next'         => 'second',
		'buttons'      => array(
			array('name'=>'Previous','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$createLink';}"),

			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Previously defined Starting date',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#platform-grid_c0',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'second',
		'title'        => 'To Date',
		'next'         => 'third',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('firstpdf');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Previously defined end date',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#platform-grid_c1',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'third',
		'title'        => 'PDF file',
		'next'         => 'fourth',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('second');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'The PDF title that was downloaded',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#platform-grid_c2',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'fourth',
		'title'        => 'Created at',
		'next'         => 'fifth',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('third');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'The date that this pdf was downloaded',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#platform-grid_c3',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'fifth',
		'title'        => 'Option view',
		'next'         => 'six',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){ $('#yw1').addClass('showhideitem'); guiders.hideAll(); $('.highlight pre').hide(); guiders.show('fourth'); }"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'View this item alone',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-eye',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'six',
		'title'        => 'Option edit',
		'next'         => 'seven',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('fifth');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'update this item',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-pencil-square-o',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php
$continueTour = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=seventeen'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'seven',
		'title'        => 'Option remove',

		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('six');}"
			),

			array('name'=>'Continue ','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$continueTour';}"),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Delete this item',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-times',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>

protected/views/pdf/create.php
<?php
/* @var $this PdfController */
/* @var $model Pdf */
$this->pageTitle = "PDF | Create";

$this->breadcrumbs = array('PDF File' => array('index'), 'Download',);
?>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <div class="col-sm-9"> <?php
                        $this->widget('booster.widgets.TbButtonGroup',
                            array(
                                'size' => 'small',
                                'context' => 'info',
                                'buttons' => array(
                                    array(
                                        'label' => 'Manage',
                                        'buttonType' =>'link',
                                        'url' => array('pdf/admin')
                                    ),
                                ),

                            )
                        );
                        ?></div>
                    <div class="col-sm-3" style="text-align: left;">
                       <?php echo Yii::app()->params['statement']['previousPage']; ?>




                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <?PHP
                            foreach(Yii::app()->user->getFlashes() as $key => $message) {
                                echo '<div class="alert alert-' . $key . '">' . $message . "</div>";
                            }
                            ?>
                        </div>
                    </div>
                    <?php $this->renderPartial('_form', array('model' => $model)); ?>
                </div>
            </div>
        </div>
</section>