protected/modules/management/controllers/UserController.php
<?php

class UserController extends BaseController
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */


    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('index','view','update','status','create','admin','delete','updatePassword','edit'),
                'users'=>array('admin'),
            ),

            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }


    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {


        if(isset($_POST['skin']))
            Yii::app()->session['skin'] = $_POST['skin'];
        $model=new User;
        $model->setScenario('create');

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if(isset($_POST['User']))
        {

            if(!empty($_POST['User']['profile_pic']))
            {
                $valid = $this->validateImageUploader($model, 'profile_pic', 'User_profile_pic_' . time());

            }

            $model->attributes=$_POST['User'];


            $valid  = true;
            $model->profile_pic = null;
            $valid = $this->validateProfileImageUploader($model,'profile_pic','user/'.$model->id.'__'.md5('profile_image'.time()).'_'.time());
            $model->attributes=$_POST['User'];
            $model->created_at = date('Y-m-d H:i:s');
            $model->gender = $_POST['User']['gender'];

            $model->background_color=Yii::app()->session['skin'];

            $model->active=1;
            if($valid) {
                if ($model->save()) {
                    Yii::app()->user->setFlash('create','Thank you for add conetns ... . .... ');
                    $this->redirect(array('view', 'id' => $model->id));
                }
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }


    public function actionEdit(){
        if(isset($_POST)){
            if(isset($_POST['name']) && isset($_POST['value']) && isset($_POST['pk']) && isset($_POST['scenario'])){
                $model = $this->loadModel($_POST['pk']);

                if(!empty($_POST['name'])){
                    $name = $_POST['name'];
                    $value = $_POST['value'];
                    $model->$name = $value;
                    if($model->save())
                        echo true;
                    else
                        echo false;
                }
            }

        }
    }


    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        if(!isset(Yii::app()->session['skin'])) {
            Yii::app()->session['skin'] = $model->background_color;

        }
        $model->setScenario('update');


        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        $valid=true;
        if(isset($_POST['User']))
        {

            $Media = $model->profile_pic;



            if (!$this->FileEmpty($model, 'profile_pic')) {
                if (!$this->GetFileType($model, $Media, 'image')) {
                    /*                    $model->addError('profile_pic', 'It seems you Didn\'t upload a proper image file ..');*/
                    $valid = true;
                } else {
                    $model->profile_pic = $Media;
                }
            } else {
                if(!$this->GetFileType($model,'profile_pic','image','upload')){
                    $model->addError('profile_pic',"It seems you Didn't upload a proper image file ..");
                    $valid=false;
                }else
                    $model->profile_pic = $this->uploader($model, 'profile_pic', 'profile_pic_edit_id' . $model->id . '_' . time());
            }


            $model->attributes=$_POST['User'];
            $model->background_color = Yii::app()->session['skin'];
            $model->gender = $_POST['User']['gender'];

            if($valid) {
                if ($model->save()) {
                    Yii::app()->user->setFlash('update','Thank you for add conetns ... . .... ');

                    $this->redirect(array('view','id'=>$model->id));
                }
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {

        if($id != Yii::app()->user->id) {
            $model = $this->loadModel($id);
            $model->deleted = 1;
            $model->save();
        }
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $model=new User('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['User']))
            $model->attributes=$_GET['User'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {

        $model=new User('search');
        $model->unsetAttributes();  // clear any default values

        if(isset($_GET['User'])) {
            $this->data_search = $_GET['User'];
            $this->data_search($model);
            $model->attributes = $_GET['User'];
            $model->deleted = 0;
        }
        $this->render('admin', array(
            'model' => $model,
        ));


    }
    public function actionUpdatePassword($id){

        $model = new ProfileForm();
        $user = $this->loadModel($id);
        $model->setScenario('updatePassword');
        $this->performAjaxValidation($model);

        $valid=true;
        if(isset($_POST['ProfileForm'])) {

            if ($_POST['ProfileForm']['new_password'] != $_POST['ProfileForm']['confirm_password']) {
                $model->addError('new_password', "<b>Passwords does not match</b>");
                $valid = false;
            }
            if ($valid) {
                $user->password = md5($_POST['ProfileForm']['new_password']);

                if ($user->save()) {
                    $_POST['updated'] = true;
                    $this->redirect(array('view','id'=>$user->id));

                }
            }
        }
        $this->render('updatePassword',array(
            'model'=>$model,
            'model_id'=>$user
        ));

    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=User::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    public function actionStatus($id)
    {


        $model=$this->loadModel($id);
        $model->setScenario('activate');

        if($id != Yii::app()->user->id) {
            if ($model->active == 0) {
                $model->active = 1;
            } else {
                $model->active = 0;
            }
        }
        if($model->save()) {
            $this->redirect(array('admin','id'=>$model->id));

        }


    }


    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']))
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/management/views/default/_adv_search_date.php
<?php
/* @var $this DefaultController */
/* @var $model PostQueue */
/* @var $form TbActiveForm */
$form = $this->beginWidget('booster.widgets.TbActiveForm',
    array(
        'id' => 'search-form',
        'type' => 'horizontal',
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    )
);
?>
<style>
    span.required {
        display: none;
    }

</style>
<br />
 <div class="row">


    <div class="col-sm-6">


        <?PHP
        echo $form->datePickerGroup(
            $model,
            'schedule_date',
            array(
                'widgetOptions' => array(
                    'options' => array(
                        'viewformat' => 'yyyy-mm-dd',
                        'format' => 'yyyy-mm-dd',
                    ),
                ),
                'labelOptions' => array(
                    'class' => 'col-sm-3'
                ),
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-9 col-sm-pull-1',
                    'style' => 'padding-left: 14px;'
                ),
            )
        );


        ?></div>
    <div class="col-sm-6">

        <?PHP
        echo $form->datePickerGroup(
            $model,
            'to',
            array(
                'widgetOptions' => array(
                    'options' => array(
                        'viewformat' => 'yyyy-mm-dd',
                        'format' => 'yyyy-mm-dd',
                    )
                ),
                'labelOptions' => array(
                    'class' => 'col-sm-3'
                ),
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-9 col-sm-pull-1',
                    'style' => 'padding-left: 14px;'
                ),
            )
        );
        ?></div>

</div>
<?PHP $this->endWidget(); ?>

protected/modules/management/views/default/_info.php
<?PHP /* @var $this DefaultController */ ?>
 <!--   <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">CPU Traffic</span>
                <span class="info-box-number"><?PHP /*echo $server_cpu */?><small>%</small></span>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-ios-speedometer"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Memory</span>
                <span class="info-box-number"><?PHP /*echo $server_memory */?><small></small></span>
            </div>
        </div>
    </div>-->
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-users"></i></span>

            <div class="info-box-content">
                <span class="info-box-text"><?PHP echo TbHtml::link('Users',$this->createUrl('user/admin'))?></span>
                <span class="info-box-number"><?PHP echo User::model()->get_number_user() ?></span>
            </div>
        </div>
    </div>

protected/modules/management/views/default/_info_category.php
<?php
/* @var $data Category */
/* @var $total DefaultController */
$total_news = count($data->news);
?>

<div class="progress-group">
    <span class="progress-text"><?PHP echo $data->title ?></span>
    <span class="progress-number"><b><?php echo $total_news   ?></b>/<?PHP echo $total ?></span>
    <div class="progress sm">
        <div class="progress-bar progress-bar-<?php echo $color ?>" style="width: <?PHP if($total_news) echo number_format( ($total_news/$total) * 100, 2 )  ?>%"></div>
    </div>
</div>

protected/modules/management/views/default/_info_category_and_news.php
<?PHP
/* @var $category Category */
/* @var $this DefaultController */
/* @var $all_news DefaultController */
?>
<div class="col-md-12">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Section Report</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-sm-12">
                    <?PHP
                    $counter = 0;
                    $class = array(
                        'aqua',
                        'red',
                        'green',
                        'yellow',
                    );
                    foreach ($category as $item) {
                        $this->renderPartial('_info_category', array('data' => $item, 'total' => $all_news, 'color' => $class[$counter]));
                        $counter++;
                        if ($counter == 3)
                            $counter = 0;
                    } ?>
                </div>
            </div>
        </div>
    </div>
</div>

protected/modules/management/views/default/index.php
<?php
/* @var $this DefaultController */
/* @var $server_cpu DefaultController */
/* @var $server_memory DefaultController */
/* @var $category Category */
/* @var $all_news News */

$this->breadcrumbs=array(
	$this->module->id,
);
$this->pageTitle = "Management";
?>
<section class="content">
	<div class="row">
	<?PHP $this->renderPartial('_info',array('this',$this,'server_memory'=>$server_memory,'server_cpu'=>$server_cpu)) ?>
		</div>
		<div class="row">
			<div class="col-sm-12">
<!--			<div class="col-sm-7 pull-right">
			<?php /*echo TbHtml::button('General',array('id'=>'btn_12','class'=>'btn btn-active'))*/?>
			<?php /*echo TbHtml::link('Posts',array('/management/default/total_posts'),array('class'=>'btn btn-link'))*/?>
</div>-->
				<div class="col-sm-6">
			<?PHP $this->renderPartial('_info_category_and_news',array(
		'this'=>$this,
		'server_memory'=>$server_memory,
		'server_cpu'=>$server_cpu,
		'category'=>$category,
		'all_news'=>$all_news
		)) ?></div>
				<div class="col-sm-6">
					<?php
					$this->renderPartial('total_posts',array('total_posts'=>$total_posts,'model'=>$model));
					?>
				</div>
			</div>
		</div>
</section>

protected/modules/management/views/default/index_old.php
<?php
/* @var $this DefaultController */

$this->breadcrumbs=array(
	$this->module->id,
);
?>
<h1><?php echo $this->uniqueId . '/' . $this->action->id; ?></h1>

<p>
This is the view content for action "<?php echo $this->action->id; ?>".
The action belongs to the controller "<?php echo get_class($this); ?>"
in the "<?php echo $this->module->id; ?>" module.
</p>
<p>
You may customize this page by editing <tt><?php echo __FILE__; ?></tt>
</p>