protected/modules/management/controllers/UserController.php
<?php

class UserController extends BaseController
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */


    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('index','view','update','status','create','admin','delete','updatePassword','edit'),
                'users'=>array('admin'),
            ),

            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }


    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {


        if(isset($_POST['skin']))
            Yii::app()->session['skin'] = $_POST['skin'];
        $model=new User;
        $model->setScenario('create');

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if(isset($_POST['User']))
        {

            if(!empty($_POST['User']['profile_pic']))
            {
                $valid = $this->validateImageUploader($model, 'profile_pic', 'User_profile_pic_' . time());

            }

            $model->attributes=$_POST['User'];


            $valid  = true;
            $model->profile_pic = null;
            $valid = $this->validateProfileImageUploader($model,'profile_pic','user/'.$model->id.'__'.md5('profile_image'.time()).'_'.time());
            $model->attributes=$_POST['User'];
            $model->created_at = date('Y-m-d H:i:s');
            $model->gender = $_POST['User']['gender'];

            $model->background_color=Yii::app()->session['skin'];

            $model->active=1;
            if($valid) {
                if ($model->save()) {
                    Yii::app()->user->setFlash('create','Thank you for add conetns ... . .... ');
                    $this->redirect(array('view', 'id' => $model->id));
                }
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }


    public function actionEdit(){
        if(isset($_POST)){
            if(isset($_POST['name']) && isset($_POST['value']) && isset($_POST['pk']) && isset($_POST['scenario'])){
                $model = $this->loadModel($_POST['pk']);

                if(!empty($_POST['name'])){
                    $name = $_POST['name'];
                    $value = $_POST['value'];
                    $model->$name = $value;
                    if($model->save())
                        echo true;
                    else
                        echo false;
                }
            }

        }
    }


    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        if(!isset(Yii::app()->session['skin'])) {
            Yii::app()->session['skin'] = $model->background_color;

        }
        $model->setScenario('update');


        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        $valid=true;
        if(isset($_POST['User']))
        {

            $Media = $model->profile_pic;



            if (!$this->FileEmpty($model, 'profile_pic')) {
                if (!$this->GetFileType($model, $Media, 'image')) {
                    /*                    $model->addError('profile_pic', 'It seems you Didn\'t upload a proper image file ..');*/
                    $valid = true;
                } else {
                    $model->profile_pic = $Media;
                }
            } else {
                if(!$this->GetFileType($model,'profile_pic','image','upload')){
                    $model->addError('profile_pic',"It seems you Didn't upload a proper image file ..");
                    $valid=false;
                }else
                    $model->profile_pic = $this->uploader($model, 'profile_pic', 'profile_pic_edit_id' . $model->id . '_' . time());
            }


            $model->attributes=$_POST['User'];
            $model->background_color = Yii::app()->session['skin'];
            $model->gender = $_POST['User']['gender'];

            if($valid) {
                if ($model->save()) {
                    Yii::app()->user->setFlash('update','Thank you for add conetns ... . .... ');

                    $this->redirect(array('view','id'=>$model->id));
                }
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {

        if($id != Yii::app()->user->id) {
            $model = $this->loadModel($id);
            $model->deleted = 1;
            $model->save();
        }
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $model=new User('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['User']))
            $model->attributes=$_GET['User'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {

        $model=new User('search');
        $model->unsetAttributes();  // clear any default values

        if(isset($_GET['User'])) {
            $this->data_search = $_GET['User'];
            $this->data_search($model);
            $model->attributes = $_GET['User'];
            $model->deleted = 0;
        }
        $this->render('admin', array(
            'model' => $model,
        ));


    }
    public function actionUpdatePassword($id){

        $model = new ProfileForm();
        $user = $this->loadModel($id);
        $model->setScenario('updatePassword');
        $this->performAjaxValidation($model);

        $valid=true;
        if(isset($_POST['ProfileForm'])) {

            if ($_POST['ProfileForm']['new_password'] != $_POST['ProfileForm']['confirm_password']) {
                $model->addError('new_password', "<b>Passwords does not match</b>");
                $valid = false;
            }
            if ($valid) {
                $user->password = md5($_POST['ProfileForm']['new_password']);

                if ($user->save()) {
                    $_POST['updated'] = true;
                    $this->redirect(array('view','id'=>$user->id));

                }
            }
        }
        $this->render('updatePassword',array(
            'model'=>$model,
            'model_id'=>$user
        ));

    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=User::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    public function actionStatus($id)
    {


        $model=$this->loadModel($id);
        $model->setScenario('activate');

        if($id != Yii::app()->user->id) {
            if ($model->active == 0) {
                $model->active = 1;
            } else {
                $model->active = 0;
            }
        }
        if($model->save()) {
            $this->redirect(array('admin','id'=>$model->id));

        }


    }


    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']))
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/management/views/user/_passwordForm.php
<?php
/* @var $this ProfileFormController */
/* @var $model ProfileForm */
/* @var $form TbActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
	'id'=>'profile-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>true,
	'type' => 'horizontal',
    'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>


    <?php
    echo $form->passwordFieldGroup($model,'new_password',array(

        'labelOptions'=>array(
            'class'=>'col-sm-2 passwords'
        ),
        'wrapperHtmlOptions' => array(
            'class' => 'col-sm-8 passwords',

        ),


    ) );
    ?>

            <?php
            echo $form->passwordFieldGroup($model,'confirm_password',array(
                'labelOptions'=>array(
                    'class'=>'col-sm-2 passwords'
                ),
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-8 passwords',
                ),
            ) );
            ?>


	<div class="form-actions  pull-right" style="margin-bottom: 20px;margin-right:20px;">
		<?php $this->widget(
			'booster.widgets.TbButton',
			array(
				'buttonType' => 'submit',
				'context' => 'primary',
				'label' => $model ? 'update' : 'Save'
			)
		); ?>

	</div>
	<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/management/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->pageTitle = "Users";

$this->breadcrumbs=array(
	'Management'=>array('/'.$this->module->id),
	'Users'=>array('index'),
	'Manage',
);



Yii::app()->clientScript->registerScript('search', "
$('#form-visible').change(function(){
	$(this).submit();
	return true;
});
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>	<style>
    .checkbox {
        display: block;
        min-height: 0px;
        margin-top: 4px;
        margin-bottom: 0px;
        padding-left: 17px;
    }
    .input-group-addon input[type=radio], .input-group-addon input[type=checkbox] {
        margin-top: 0;
    }
    .radio input[type=radio], .radio-inline input[type=radio], .checkbox input[type=checkbox], .checkbox-inline input[type=checkbox] {
        float: left;
        margin-left: -16px;
    }
</style>

<section class="content">
	<div class="row">
		<div class="col-sm-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<div class="col-sm-9"> <?PHP
						$this->widget(
							'booster.widgets.TbButtonGroup',
							array(
								'size' => 'small',
								'context' => 'info',
								'buttons' => array(
									array(
										'label' => 'Create',
										'buttonType' =>'link',
										'url' => array('user/create')
									),
								),
								/*'htmlOptions'=>array(
                                    'class'=>'pull-right	'
                                )*/
							)
						);

						?></div>
					<div class="col-sm-3" style="text-align:left;">
						<?php echo Yii::app()->params['statement']['previousPage']; ?>




					</div>
				</div>
				<div class="box-body">
					<?PHP //echo $this->renderPartial('_search',array('model'=>$model),true) ?>

					<?PHP
					$form=$this->beginWidget('booster.widgets.TbActiveForm', array(
						'action'=>Yii::app()->createUrl($this->route),
						'method'=>'get',
						'id'=>'form-visible',
					));
					?>
					<div class="col-sm-2 pull-left page-sizes"  >

						<?php echo $form->dropDownListGroup(
							$model,
							'pagination_size',
							array(

								'widgetOptions'=>array(
									'data'=>$model->pages_size(),
									'htmlOptions'=>array(

									),
								),
								'hint'=>''
							)
						); ?>
					</div>
					<?php
					$this->endWidget();
					$this->widget('booster.widgets.TbGridView', array(
						'id' => 'user-grid',
						'type' => 'striped bordered condensed',
						'template' => '{pager}{items}{summary}',
						'enablePagination' => true,
						'pager' => array(
							'class' => 'booster.widgets.TbPager',
							'nextPageLabel' => 'Next',
							'prevPageLabel' => 'Previous',
							'htmlOptions' => array(
								'class' => 'pull-right'
							)
						),
						'htmlOptions' => array(
							'class' => 'table-responsive'
						),
						'dataProvider' => $model->search(),
						'filter' => $model,
						'columns' => array(

							array(
								'class' => 'booster.widgets.TbEditableColumn',
								'name' => 'name',
								'sortable' => true,
								'editable' => array(
									'url' => $this->createUrl('user/edit'),
									'placement' => 'right',
									'inputclass' => 'span1'
								),

								'visible'=>$model->visible_name?true:false,
							),
							array(
								'name'=>'username',
								'visible'=>$model->visible_username?true:false,
							),
							array(
								'class' => 'booster.widgets.TbEditableColumn',
								'name' => 'active',
								'type'=>'raw',
								'value'=>'CHtml::link($data->active?CHtml::tag("span",array("class"=>"label label-success"),"Active",true):CHtml::tag("span",array("class"=>"label label-danger"),"Disabled",true),"#",array("data-value"=>$data->active,"rel"=>"User_active","data-pk"=>$data->id,"class"=>"editable editable-click"))',
								'sortable' => true,
								'editable' => array(
									'type' => 'select2',
									'url' => $this->createUrl('user/edit'),
									'placement' => 'right',
									'inputclass' => 'span3',
									'source' => array('0'=>'Disabled','1'=>'Active'),
								),
								'visible'=>$model->visible_f_name?true:false,
							),
							array(
								'class' => 'booster.widgets.TbEditableColumn',
								'name' => 'gender',
								'type'=>'raw',
								'value'=>'CHtml::link($data->gender == "m" ?CHtml::tag("span",array("class"=>"label label-success"),"Male",true):CHtml::tag("span",array("class"=>"label label-warning"),"Female",true),"#",array("data-value"=>$data->active,"rel"=>"User_gender","data-pk"=>$data->id,"class"=>"editable editable-click"))',
								'sortable' => true,
								'editable' => array(
									'type' => 'select2',
									'url' => $this->createUrl('user/edit'),
									'placement' => 'right',
									'inputclass' => 'span3',
									'source' => array('f'=>'Female','m'=>'Male'),
								),
								'visible'=>$model->visible_f_name?true:false,
							),
							array(
							'name'=>'email',
								'type'=>'raw'
							),


							array(
								'name'=>'profile_pic',
								'type'=>'html',
 								'header'=>'Media',
								'htmlOptions'=>array('width'=>'150px'),
								'value'=>function($model){
									if(!empty($model->profile_pic)){
										echo CHtml::image($model->profile_pic,$model->profile_pic,array("class"=>"img-responsive img-tb-grid-view"));

									}else {
									if
										($model->gender == "m"){
											echo CHtml::image(Yii::app()->BaseUrl . '/temp/dist/img/avatar5.png', Yii::app()->BaseUrl . '/temp/dist/img/avatar5.png', array("class" => "img-responsive img-tb-grid-view"));
										}else{
											echo CHtml::image(Yii::app()->BaseUrl . '/temp/dist/img/avatar2.png', Yii::app()->BaseUrl . '/temp/dist/img/avatar2.png', array("class" => "img-responsive img-tb-grid-view"));
										}
									 }
								}
							),
						/*	array(
								'name'=>'created_at',
								'visible'=>$model->visible_created_at?true:false,
							),*/
 							array(
								'class' => 'booster.widgets.TbButtonColumn',
								'header' => 'Options',
								'template' => '{view}{update}{activate}{deactivate}{delete}',
								'buttons' => array(
									'view' => array(
										'label' => 'View',
										'icon' => 'fa fa-eye',
									),
									'update' => array(
										'label' => 'Update',
										'icon' => 'fa fa-pencil-square-o',
									),
									'delete' => array(
										'label' => 'Delete',
										'visible'=>'$data->id == Yii::app()->user->id ? false : true',
										'icon' => 'fa fa-times',
									),

								/*	'delete' => array(
										'label' => 'Delete',
										'icon' => 'fa fa-times',
									),*/

									'activate' => array(
										'label' => 'Deactivate',
										'url' => 'Yii::app()->createUrl(Yii::app()->controller->module->id."/".Yii::app()->controller->id."/status", array("id"=>$data->id))',
										'icon' => 'fa fa-toggle-off',
										'visible' => '($data->active == 1) and ($data->id == Yii::app()->user->id ? false : true)',
										'click' => "function(){

				$.fn.yiiGridView.update('user-grid', {
				type:'POST',
				url:$(this).attr('href'),
				success:function(data) {
				$.fn.yiiGridView.update('user-grid');}});return false;}",
									),
									'deactivate' => array(
										'label' => 'Activate',
										'url' => 'Yii::app()->createUrl(Yii::app()->controller->module->id."/".Yii::app()->controller->id."/status", array("id"=>$data->id))',
										'icon' => 'fa fa-toggle-on',
										'visible' => '($data->active == 0) and ($data->id == Yii::app()->user->id ? false : true)',
										'click' => "function(){
				$.fn.yiiGridView.update('user-grid', {
				type:'POST',
				url:$(this).attr('href'),
				success:function(data) {
				$.fn.yiiGridView.update('user-grid');}});return false;}"
									),

								)
							),						))); ?>
				</div>
			</div>
		</div>
	</div>




 </section>

protected/modules/management/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->pageTitle = "Users | Create";

$this->breadcrumbs=array(
	'Management'=>array('/'.$this->module->id),
	'Users'=>array('index'),
	'Create',
);


?>

<section class="content">
	<div class="row">
		<div class="col-sm-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<div class="col-sm-9"><?PHP
						$this->widget(
							'booster.widgets.TbButtonGroup',
							array(
								'size' => 'small',
								'context' => 'info',
								'buttons' => array(
									array(
										'label' => 'Manage',
										'buttonType' =>'link',
										'url' => array('user/admin')
									),
								),
								/*'htmlOptions'=>array(
                                    'class'=>'pull-right	'
                                )*/
							)
						);

						?></div>
					<div class="col-sm-3" style="text-align: left;">
						<?php echo Yii::app()->params['statement']['previousPage']; ?>




					</div>
				</div>
				<div class="box-body">
					<?php $this->renderPartial('_form', array('model'=>$model)); ?>
				</div>
			</div>
		</div>
</section>

protected/modules/management/views/user/update.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->pageTitle = "Users | Update";

$this->breadcrumbs=array(
	'Management'=>array('/'.$this->module->id),
	'Users'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);


?>

	<section class="content">
		<div class="row">
			<div class="col-sm-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<div class="col-sm-9"><h2>        <?php $this->widget(
									'booster.widgets.TbButtonGroup',
									array(
										'size' => 'small',
										'context' => 'info',
										'buttons' => array(
											array(
												'label' => 'Update password',
												'buttonType' => 'link',
												'url' => array('/management/user/updatePassword/', 'id' => $model->id)
											),
										),
									)
								); ?></h2></div>
						<div class="col-sm-3" style="padding-top: 19px;text-align: left;">
							<div class="col-sm-7"><?php echo Yii::app()->params['statement']['previousPage']; ?></div>

							<div class="col-sm-5">
								<?PHP
								$this->widget(
									'booster.widgets.TbButtonGroup',
									array(
										'size' => 'small',
										'context' => 'info',
										'buttons' => array(
											array(
												'label' => 'Manage',
												'buttonType' => 'link',
												'url' => array('user/admin')
											),
										),
										/*'htmlOptions'=>array(
                                            'class'=>'pull-right	'
                                        )*/
									)
								);

								?>
							</div>
						</div>
					</div>
					<div class="box-body">
						<?php $this->renderPartial('_form', array('model' => $model)); ?>
					</div>
				</div>
			</div>
	</section>

protected/modules/management/views/user/updatePassword.php
<?php
/* @var $this ProfileFormController */
/* @var $model ProfileForm */

$this->pageTitle = "Users | Update";


?>


    <section class="content">
        <div class="row">
            <div class="col-sm-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <?php
                        if (isset($_POST['updated'])) {
                            echo '<div class="alert alert-info">Updated</div>';
                        }
                        ?>
                        <div class="col-sm-9"><h2>
                                <?php $this->widget(
                                    'booster.widgets.TbButtonGroup',
                                    array(
                                        'size' => 'small',
                                        'context' => 'info',
                                        'buttons' => array(
                                            array(
                                                'label' => 'Update profile',
                                                'buttonType' => 'link',
                                                'url' => array('/management/user/update/', 'id' => $model_id->id)
                                            ),
                                        ),
                                    )
                                ); ?></h2></div>
                        <div class="col-sm-3" style="padding-top: 19px;text-align: left;">
                            <div class="col-sm-7"><?php echo Yii::app()->params['statement']['previousPage']; ?></div>
                            <div class="col-sm-5">
                                <?PHP
                                $this->widget(
                                    'booster.widgets.TbButtonGroup',
                                    array(
                                        'size' => 'small',
                                        'context' => 'info',
                                        'buttons' => array(
                                            array(
                                                'label' => 'Manage',
                                                'buttonType' => 'link',
                                                'url' => array('user/admin')
                                            ),
                                        ),
                                        /*'htmlOptions'=>array(
                                            'class'=>'pull-right	'
                                        )*/
                                    )
                                );

                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="box-body">
                        <?php $this->renderPartial('_passwordForm', array('model' => $model)); ?>
                    </div>
                </div>
            </div>
    </section>

protected/modules/management/views/user/view.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->pageTitle = "Users | View";

$this->breadcrumbs=array(
	'Management'=>array('/'.$this->module->id),
	'Users'=>array('index'),
	$model->name,



);
?>
<section class="content">
	<section class="content">
		<?PHP if(Yii::app()->user->hasFlash('create')){ ?>
			<div class="callout callout-success" style="margin-top:20px;">
				<h4>New user have been added successfully. </h4>
			</div>

		<?PHP } if(Yii::app()->user->hasFlash('update')){ ?>
			<div class="callout callout-info" style="margin-top:20px;">
				<h4>user updated successfully. </h4>
			</div>
		<?php } ?>
	<div class="row">
		<div class="col-sm-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<div class="col-sm-9"><?PHP
						$this->widget(
							'booster.widgets.TbButtonGroup',
							array(
								'size' => 'small',
								'context' => 'info',
								'buttons' => array(
									array(
										'label' => 'Action',
										'items' => array(
 											array('label' => 'Update', 'url'=>array('update', 'id'=>$model->id)),
											array('label' => 'Delete', 'url' => '#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
											array('label' => 'Manage', 'url'=>array('admin'))
										)
									),
									array('label' => 'Create','buttonType'=>'link', 'url'=>array('create'),								'context' => 'info',
										'context' => 'success',
										'htmlOptions' => array('class' => 'btns-positions'), // for inset effect


									),
								),
								/*	'htmlOptions'=>array(
                                        'class'=>'pull-right	'
                                    )*/
							)
						);
						?></div>
					<div class="col-md-3" style="text-align: left;">
						<?php echo Yii::app()->params['statement']['previousPage']; ?>




					</div>
				</div>
				<div class="box-body">
					<?php $this->widget('booster.widgets.TbDetailView', array(
						'data'=>$model,
						'attributes'=>array(
							'id',
							'name',
							'username',
							'created_at'
						),
					)); ?>
				</div>
			</div>
		</div>
</section>